向量：

In [1]:
import numpy as np

v = np.array([1, 2, 3])
v

array([1, 2, 3])

向量元素个数：

In [2]:
len(v)

3

向量的模：

In [3]:
def norm(v):
    squares = [i**2 for i in v]
    return sum(squares)**0.5

norm(v)

3.7416573867739413

In [4]:
import numpy.linalg as lin

lin.norm(v)

3.7416573867739413

In [5]:
import numpy as np

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

加：

In [6]:
A + B

array([5, 7, 9])

减：

In [7]:
A - B

array([-3, -3, -3])

标量乘：

In [8]:
2 * A

array([2, 4, 6])

点乘：

In [9]:
import numpy as np

np.dot(A, B)

32

两个向量的夹角：

In [10]:
import numpy as np
import numpy.linalg as lin

def angle(A, B):
    cos_theta = np.dot(A, B) / lin.norm(A) / lin.norm(B)
    return np.arccos(np.clip(cos_theta, -1, 1)) * 180 / np.pi

angle(A, B)

12.933154491899135

矩阵：

In [11]:
import numpy as np

M = np.array([
    [1,2,3],
    [4,5,6]
])
M

array([[1, 2, 3],
       [4, 5, 6]])

矩阵的大小：

In [12]:
M.shape

(2, 3)

矩阵元素个数

In [13]:
M.size

6

方阵：

In [14]:
import numpy as np

np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

三角矩阵：

In [15]:
import numpy as np

np.array([
    [1,2,3],
    [0,5,6],
    [0,0,9]
])

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [16]:
import numpy as np

np.array([
    [1,0,0],
    [4,5,0],
    [7,8,9]
])

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

对角矩阵：

In [17]:
import numpy as np

np.array([
    [1,0,0],
    [0,5,0],
    [0,0,9]
])

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

单位矩阵：

In [18]:
import numpy as np

np.array([
    [1,0,0],
    [0,1,0],
    [0,0,1]
])

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [19]:
import numpy as np
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
import numpy as np

A = np.array([
    [1,2,3],
    [4,5,6]
])
B = np.array([
    [3,2,1],
    [6,5,4]
])
C = np.array([
    [1,2],
    [3,4],
    [5,6]
])

矩阵加法：

In [21]:
A + B

array([[ 4,  4,  4],
       [10, 10, 10]])

矩阵的减法：

In [22]:
A - B

array([[-2,  0,  2],
       [-2,  0,  2]])

矩阵与标量的乘法：

In [23]:
2 * A

array([[ 2,  4,  6],
       [ 8, 10, 12]])

矩阵与矩阵的乘积：

In [24]:
import numpy as np

np.dot(A, C)

array([[22, 28],
       [49, 64]])

矩阵的转置：

In [25]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

逆矩阵：

In [26]:
import numpy as np
import numpy.linalg as lin

M = np.array([
    [1,2],
    [-1,-3]
])

M_inv = lin.inv(M)
M_inv

array([[ 3.,  2.],
       [-1., -1.]])

In [27]:
import numpy as np

np.dot(M, M_inv)

array([[1., 0.],
       [0., 1.]])

伪逆矩阵：

In [28]:
import numpy as np
import numpy.linalg as lin

M = np.array([
    [1,2,3],
    [4,5,6]
])

M_pinv = lin.pinv(M)
M_pinv

array([[-0.94444444,  0.44444444],
       [-0.11111111,  0.11111111],
       [ 0.72222222, -0.22222222]])

行列式：

In [29]:
import numpy as np
import numpy.linalg as lin

M = np.array([
    [1,2],
    [3,4]
])

lin.det(M)

-2.0000000000000004

In [30]:
import numpy as np
import numpy.linalg as lin

M = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

lin.det(M)

0.0

特征值与特征向量：

In [31]:
import numpy as np
import numpy.linalg as lin

M = np.array([
    [1,2],
    [3,4]
])

eigenvalues, eigenvectors = lin.eig(M)

In [32]:
eigenvalues

array([-0.37228132,  5.37228132])

In [33]:
eigenvectors

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])

奇异值分解：

In [34]:
import numpy as np
import numpy.linalg as lin

M = np.array([
    [1,2],
    [3,4]
])

U, S, V_T = lin.svd(M)

In [35]:
U

array([[-0.40455358, -0.9145143 ],
       [-0.9145143 ,  0.40455358]])

In [36]:
np.diag(S)

array([[5.4649857 , 0.        ],
       [0.        , 0.36596619]])

In [37]:
V_T

array([[-0.57604844, -0.81741556],
       [ 0.81741556, -0.57604844]])

In [38]:
U.dot(np.diag(S)).dot(V_T)

array([[1., 2.],
       [3., 4.]])

矩阵的迹：

In [39]:
import numpy as np

M = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

np.trace(M)

15